<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="regression-challenge---linear-model-interpretability" class="level1">
<h1>🗑️ Regression Challenge - Linear Model Interpretability</h1>
<section id="challenge-overview" class="level2">
<h2 class="anchored" data-anchor-id="challenge-overview">Challenge Overview</h2>
<p><strong>Your Mission:</strong> Create a comprehensive Quarto document that demonstrates the dangers of trusting linear models when relationships are non-linear, analyzes the interpretability issues that arise, and presents compelling visual evidence of why we need to be skeptical of regression results. Then render the document to HTML and deploy it via GitHub Pages using the starter repository workflow.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>⚠️ AI Partnership Required
</div>
</div>
<div class="callout-body-container callout-body">
<p>This challenge pushes boundaries intentionally. You’ll tackle problems that normally require weeks of study, but with Cursor AI as your partner (and your brain keeping it honest), you can accomplish more than you thought possible.</p>
<p><strong>The new reality:</strong> The four stages of competence are Ignorance → Awareness → Learning → Mastery. AI lets us produce Mastery-level work while operating primarily in the Awareness stage. I focus on awareness training, you leverage AI for execution, and together we create outputs that used to require years of dedicated study.</p>
</div>
</div>
</section>
<section id="problem-violating-the-assumption-of-linearity" class="level2">
<h2 class="anchored" data-anchor-id="problem-violating-the-assumption-of-linearity">Problem Violating the Assumption of Linearity🎯</h2>
<blockquote class="blockquote">
<p>“We need to stop believing much of the empirical work we’ve been doing.” - Christopher H. Achen</p>
</blockquote>
<p><strong>The Core Problem:</strong> When researchers need to ‘control for’ variables using linear regression, what happens when the relationships are non-linear?</p>
<p><strong>What does “control for” mean?</strong> Imagine you’re studying whether social media causes anxiety. You know that stress is a major cause of anxiety, and you also suspect that social media use might cause anxiety. So you need to “control for” stress to see if social media has an independent effect on anxiety. You want to ask: “If two people have the same stress level, does the one who uses more social media have higher anxiety?”</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🎯 The Key Insight: Non-Linearity Breaks Even “Good” Regressions
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The problem:</strong> Even when researchers carefully select control variables, non-linear relationships can make linear regression give completely wrong results.</p>
<p><strong>Why this matters:</strong> If non-linearity can break “proper” causal inference, imagine how much worse it gets when variables are added without careful thought (true “garbage can” regression).</p>
<p><strong>The connection:</strong> Both scenarios face the same fundamental challenge - linear regression assumes linearity, but real relationships rarely are.</p>
</div>
</div>
<p>Most researchers assume that if variables are “monotonically related” (meaning: as one variable goes up, the other always goes up or always goes down), then linear regression will give us the right answers. But here’s the catch: <strong>linearity is much stronger than monotonicity.</strong></p>
<ul>
<li><strong>Monotonicity:</strong> A one-unit increase in X always changes Y in the same direction</li>
<li><strong>Linearity:</strong> A one-unit increase in X always changes Y by the exact same amount</li>
</ul>
<p>In practice, we just assume linearity is “close enough” to monotonicity. But what if it’s not? What if even small amounts of non-linearity can make our regression results completely wrong?</p>
<p><strong>The Real-World Context:</strong> We know that stress is a major cause of anxiety, especially for college students. We also suspect that social media use might cause anxiety. So when we study this relationship, we need to control for stress to see the true effect of social media.</p>
<p><strong>The Key Problem:</strong> But here’s where things get tricky. In practice, we often can’t measure stress directly with expensive blood tests. Instead, we use surveys and self-reports. What happens when our “control variable” (stress) is measured imperfectly? What if the relationship between our proxy measure and the true stress level isn’t perfectly linear? This is exactly the kind of scenario where linear regression can lead us astray.</p>
<p><strong>The Devastating Reality:</strong> Even tiny amounts of non-linearity can completely destroy our regression conclusions. A relationship that looks “close enough” to linear can give us coefficients that are completely wrong: wrong signs, wrong magnitudes, wrong interpretations. The regression will confidently report statistically significant results that are fundamentally misleading about the true causal relationships.</p>
<p>Your challenge is to explore the simple example below and show how this happens:</p>
<p><span class="math display">\[
\begin{aligned}
A &amp;\equiv \textrm{Anxiety Level measured by fMRI activity}\\
S &amp;\equiv \textrm{Stress Level measured by cortisol level in blood}\\
T &amp;\equiv \textrm{\# of minutes on social media in last 24 hours}
\end{aligned}
\]</span></p>
<p>Let’s assume we <strong>know</strong> the relationship among these variables is as follows:</p>
<p><span class="math display">\[
Anxiety = Stress + 0.1 \times Time
\]</span></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🔍 Understanding the True Relationship: Implied Coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Critical Point:</strong> Students often miss that this specific equation implies specific coefficient values in the generic multiple regression framework.</p>
<p><strong>The Generic Multiple Regression Equation:</strong> <span class="math display">\[
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \epsilon
\]</span></p>
<p><strong>In Our Case:</strong> <span class="math display">\[
Anxiety = \beta_0 + \beta_1 \times Stress + \beta_2 \times Time + \epsilon
\]</span></p>
<p><strong>The True Coefficients (what we “know”):</strong></p>
<ul>
<li><span class="math inline">\(\beta_0 = 0\)</span> (intercept is zero)</li>
<li><span class="math inline">\(\beta_1 = 1\)</span> (coefficient on Stress is 1)<br>
</li>
<li><span class="math inline">\(\beta_2 = 0.1\)</span> (coefficient on Time is 0.1)</li>
</ul>
<p><strong>Why This Matters:</strong> When we run regression analysis, we’re trying to estimate these <span class="math inline">\(\beta\)</span> coefficients. If our regression gives us coefficients that are very different from these true values, we know our model is wrong—even if it has good statistical fit!</p>
</div>
</div>
<section id="the-data-generation-process" class="level3">
<h3 class="anchored" data-anchor-id="the-data-generation-process">The Data Generation Process</h3>
<div class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>observDF</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Notice that <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span> indeed holds perfectly. Also, notice the addition of a <code>StressSurvey</code> column. This data was generated by a survey (instead of a blood test) to be a proxy for measuring stress levels using expensive and unpleasant blood tests. You can see it’s a good proxy as there is a <em>monotonic</em> (and a sorta-kinda <em>linear</em>) relationship between the survey results and actual measured stress levels (see <a href="#fig-stress-proxy" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📝 Methodological Note: The Contrived Nature of This Example
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Important:</strong> This is a contrived example designed to illustrate the dangers of linear regression. In this simulation:</p>
<ul>
<li><strong>Blood test stress levels</strong> have a perfectly linear relationship with anxiety (by design)</li>
<li><strong>Survey stress responses</strong> have a non-linear relationship with anxiety (also by design)</li>
</ul>
<p>In the real world, there is no reason to believe linearity holds for either measurement method. Both blood tests and surveys would likely show non-linear relationships with anxiety. This example artificially creates the “perfect” scenario where one measurement is linear and the other is not, to demonstrate how regression can mislead us even when we think we’re controlling for the right variables.</p>
</div>
</div>
<div id="cell-fig-stress-proxy" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set style</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">"whitegrid"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> (<span class="dv">7</span>, <span class="dv">4</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the plot</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>ax.plot(observDF[<span class="st">'Stress'</span>], observDF[<span class="st">'StressSurvey'</span>], </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        linewidth<span class="op">=</span><span class="dv">1</span>, color<span class="op">=</span><span class="st">'purple'</span>, marker<span class="op">=</span><span class="st">'o'</span>, markersize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"StressSurvey seems a decent (monotonic) proxy for actual Stress"</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Actual Stress Level"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Stress Survey Response"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-stress-proxy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-proxy-output-1.png" width="662" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: StressSurvey as a proxy for actual Stress levels
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="challenge-requirements" class="level2">
<h2 class="anchored" data-anchor-id="challenge-requirements">Challenge Requirements 📋</h2>
<section id="minimum-requirements-for-any-points-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="minimum-requirements-for-any-points-on-challenge">Minimum Requirements for Any Points on Challenge</h3>
<ol type="1">
<li><p><strong>Create a Quarto Document:</strong> Use the starter repository (see Repository Setup section below) to begin with a working template. Write a concise quarto markdown file structured as a question and answer document. Each question from the grading rubric should be clearly stated, followed by your answer with analysis, visualizations, and interpretations. <strong>Important:</strong> Your final rendered HTML should contain only your Q&amp;A responses—all challenge instructions, setup guides, and grading rubrics should be removed from the final report.</p></li>
<li><p><strong>Render to HTML:</strong> You must render the quarto markdown file to HTML.</p></li>
<li><p><strong>GitHub Repository:</strong> Use your forked repository (from the starter repository) named “garbageCanRegressionChallenge” in your GitHub account. Upload your rendered HTML files to this repository.</p></li>
<li><p><strong>GitHub Pages Setup:</strong> The repository should be made the source of your github pages:</p>
<ul>
<li>Go to your repository settings (click the “Settings” tab in your GitHub repository)</li>
<li>Scroll down to the “Pages” section in the left sidebar</li>
<li>Under “Source”, select “Deploy from a branch”</li>
<li>Choose “main” branch and “/ (root)” folder</li>
<li>Click “Save”</li>
<li>Your site will be available at: <code>https://[your-username].github.io/regressionChallenge/</code></li>
<li><strong>Note:</strong> It may take a few minutes for the site to become available after enabling Pages</li>
</ul></li>
</ol>
</section>
</section>
<section id="getting-started-repository-setup" class="level2">
<h2 class="anchored" data-anchor-id="getting-started-repository-setup">Getting Started: Repository Setup 🚀</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>📁 Quick Start with Starter Repository
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Step 1:</strong> Fork the starter repository to your github account at <a href="https://github.com/flyaflya/regressionChallenge.git">https://github.com/flyaflya/regressionChallenge.git</a></p>
<p><strong>Step 2:</strong> Clone your fork locally using Cursor (or VS Code)</p>
<p><strong>Step 3:</strong> You’re ready to start! The repository includes pre-loaded data and a working template.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>💡 Why Use the Starter Repository?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Benefits:</strong></p>
<ul>
<li><strong>Pre-loaded data:</strong> All required data (<code>observDF</code> with Stress, StressSurvey, Time, Anxiety) is included</li>
<li><strong>Working template:</strong> Basic Quarto structure (<code>index.qmd</code>) is ready</li>
<li><strong>No setup errors:</strong> Avoid common data loading issues</li>
<li><strong>Focus on analysis:</strong> Spend time on regression analysis, not data preparation</li>
</ul>
</div>
</div>
<section id="getting-started-tips" class="level3">
<h3 class="anchored" data-anchor-id="getting-started-tips">Getting Started Tips</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>🎯 Navy SEALs Motto
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p>“Slow is Smooth and Smooth is Fast”</p>
</blockquote>
<p><em>Take your time to understand the regression mechanics, plan your approach carefully, and execute with precision. Rushing through this challenge will only lead to errors and confusion.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>💾 Important: Save Your Work Frequently!
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Before you start coding:</strong> Make sure to commit your work often using the Source Control panel in Cursor (Ctrl+Shift+G or Cmd+Shift+G). This prevents the AI from overwriting your progress and ensures you don’t lose your work.</p>
<p><strong>Commit after each major step:</strong></p>
<ul>
<li>After completing each regression analysis</li>
<li>After finishing each challenge question</li>
<li>Before asking the AI for help with new code</li>
</ul>
<p><strong>How to commit:</strong></p>
<ol type="1">
<li>Open Source Control panel (Ctrl+Shift+G)</li>
<li>Stage your changes (+ button)</li>
<li>Write a descriptive commit message</li>
<li>Click the checkmark to commit</li>
</ol>
<p><em>Remember: Frequent commits are your safety net!</em></p>
</div>
</div>
</section>
</section>
<section id="grading-rubric" class="level2">
<h2 class="anchored" data-anchor-id="grading-rubric">Grading Rubric 🎓</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>📊 What You’re Really Being Graded On
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>This is an investigative report, not a coding exercise.</strong> You’re analyzing regression models and reporting your findings like a professional analyst would. Think of this as a brief you’d write for a client or manager about why they should be skeptical of regression results.</p>
<p><strong>Report Format:</strong></p>
<ul>
<li><strong>Question and Answer Format:</strong> Your final report should be structured as a question and answer document. Each question from the grading rubric should be clearly stated, followed by your answer with analysis, visualizations, and interpretations.</li>
<li><strong>Delete All Challenge Instructions:</strong> Once you’ve completed your analysis, remove all challenge instructions, setup guides, and grading rubrics from your final rendered HTML. The final report should contain only your Q&amp;A responses, code outputs, and visualizations—nothing else.</li>
<li><strong>Hidden Code:</strong> Tell a narrative and visual story, but hide your code (the code can be referenced in your github *.qmd source file if needed).</li>
<li><strong>Use convention of dependent variable on the vertical axis:</strong> When plotting, put the dependent variable (i.e., Anxiety) on the vertical axis. Independent variables (i.e., StressSurvey, Stress, and Time) should be on the horizontal axis.</li>
</ul>
<p><strong>What makes a great report:</strong></p>
<ul>
<li><strong>Clear narrative:</strong> Tell the story of what you discovered about regression interpretability</li>
<li><strong>Insightful analysis:</strong> Focus on the most interesting differences between true relationships and estimated relationships</li>
<li><strong>Professional presentation:</strong> Clean, readable, and engaging</li>
<li><strong>Concise conclusions:</strong> No AI babble or unnecessary technical jargon</li>
<li><strong>Human insights:</strong> Your interpretation of what the regression coefficients actually mean (or don’t mean)</li>
</ul>
<p><strong>What we’re looking for:</strong> A compelling 4-8 minute read that demonstrates both the power of linear models for interpretation and the critical pitfalls of over-relying on statistical significance in regression analysis.</p>
</div>
</div>
<section id="questions-to-answer-for-75-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-75-grade-on-challenge">Questions to Answer for 75% Grade on Challenge</h3>
</section>
</section>
<section id="question-1-bivariate-regression-analysis-with-stresssurvey" class="level2">
<h2 class="anchored" data-anchor-id="question-1-bivariate-regression-analysis-with-stresssurvey">Question 1 — Bivariate Regression Analysis with StressSurvey</h2>
<p><strong>Answer — Bivariate regression of Anxiety on StressSurvey</strong></p>
<ul>
<li>Model estimated: Anxiety = β0 + β1 × StressSurvey + ε</li>
<li>Using the provided <code>observDF</code> (15 observations), the OLS estimates (exact values computed from the data) are:
<ul>
<li>Intercept (β0) = -1.5240</li>
<li>Slope (β1) = 1.0470</li>
</ul></li>
</ul>
<p><strong>Model diagnostics and inference (from the OLS table):</strong></p>
<ul>
<li>R-squared = 0.9011 (the model explains ~90.1% of the variance in Anxiety)</li>
<li>Intercept std err = 0.707, t = -2.156, p ≈ 0.050</li>
<li>Slope std err = 0.096, t = 10.883, p ≈ 6.68e-08 (highly significant)</li>
</ul>
<p><strong>Interpretation and comparison to the true relationship:</strong></p>
<ul>
<li>The data-generating equation is: Anxiety = 1 × Stress + 0.1 × Time. The true coefficient on Stress is 1 and on Time is 0.1.</li>
<li>This bivariate regression uses <code>StressSurvey</code> (a survey proxy) rather than the true <code>Stress</code> measurement. The estimated slope (~1.047) describes the change in Anxiety for a one-unit increase in the <em>survey</em> score, not for a one-unit change in true Stress.</li>
<li>Because <code>StressSurvey</code> is a non-linear proxy for <code>Stress</code> and the variable <code>Time</code> is omitted from this bivariate model, the OLS slope does not recover the underlying causal parameter for Stress (β1 = 1) in a clean way. The coefficient is informative about association with the survey score, but it is not a causal estimate of the effect of true Stress.</li>
<li>The high R-squared and very small p-value on the slope can be misleading: they suggest a strong, statistically significant relationship, yet the coefficient conflates measurement non-linearity and omitted-variable influence (Time). This is exactly the cautionary example the challenge highlights.</li>
</ul>
<p><strong>Recommended short conclusion:</strong></p>
<ul>
<li>The naive bivariate regression of Anxiety on <code>StressSurvey</code> produces a seemingly precise slope estimate (≈1.047) and a high R-squared, but this is an association between Anxiety and the survey proxy. It should not be interpreted as recovering the true causal coefficient on Stress without further analysis (multiple regression with the true <code>Stress</code>, diagnostic plots, or sample-splitting).</li>
</ul>
<div id="02625357" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Sat, 08 Nov 2025   Prob (F-statistic):           6.68e-08
Time:                        15:38:55   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-2.png" width="662" height="373" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="question-2-visualization-of-anxiety-vs-stresssurvey" class="level2">
<h2 class="anchored" data-anchor-id="question-2-visualization-of-anxiety-vs-stresssurvey">Question 2 — Visualization of Anxiety vs StressSurvey</h2>
<p><strong>Goal:</strong> Show the bivariate pattern between the proxy <code>StressSurvey</code> (x-axis) and <code>Anxiety</code> (y-axis), overlay the fitted linear regression line, and diagnose potential issues with interpreting the apparent fit.</p>
<p><strong>Plot &amp; Fit Observations:</strong></p>
<ul>
<li>The points fall in five tight vertical clusters at survey values {0, 3, 6, 9, 12}. This discretization (survey coarseness) artificially strengthens the visual impression of linearity because there is no within-cluster horizontal variation.</li>
<li>A single straight line passes visually close to the cluster centers and produces a high R-squared (~0.90) and a highly significant slope.</li>
<li>However, the <em>jump</em> between 6 → 9 is disproportionately large because underlying true Stress jumps from 2 → 8 at that stage; the line’s slope is partly driven by this leverage-like gap rather than a smooth linear mapping of stress.</li>
<li>The negative intercept (≈ -1.52) is outside the observable range (we never see negative Anxiety). This indicates extrapolation at low survey scores is unstable.</li>
<li>Residual structure: within each cluster, residuals are near zero (design artifact), while between clusters the spacing is uneven (small differences 0→3→6 then a large gap 6→9 then moderate 9→12). This non-uniform spacing hints at a <em>piecewise</em> or <em>non-linear proxy transformation</em> rather than a single homogeneous linear effect.</li>
<li>Omitted variable <code>Time</code> still contributes 0.1 × Time to Anxiety. Because Time is mildly correlated with Stress (and thereby with StressSurvey), its effect is partially absorbed into the slope, inflating interpretability risk.</li>
</ul>
<p><strong>Key Interpretation Risks:</strong> 1. <strong>Proxy Non-Linearity:</strong> <code>StressSurvey</code> is monotonic but not linearly proportional to true Stress, so the fitted line’s slope is not the causal Stress effect. 2. <strong>Discrete X Values:</strong> Clustering hides potential curvature; with more granular survey scaling we might see local departures from linear trend. 3. <strong>Leverage Gap:</strong> The 6→9 jump acts like a leverage segment amplifying slope stability metrics (t-stat) while masking non-linearity. 4. <strong>Omitted Variable Influence:</strong> Time’s true effect (0.1 × Time) is pooled into the StressSurvey slope in this bivariate specification. 5. <strong>Misleading Goodness-of-Fit:</strong> High R-squared here is partly mechanical (few distinct x-values) and shouldn’t be over-weighted in causal interpretation.</p>
<p><strong>Concise Conclusion:</strong> The plot “looks” linear and strong, but its visual neatness is an artifact of discretized proxy measurement plus omitted variable absorption. The high R-squared and significant slope can mislead stakeholders into overconfident causal claims about survey-measured stress and anxiety.</p>
<div id="cell-fig-stressSurvey-anxiety" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-stresssurvey-anxiety" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stresssurvey-anxiety-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stresssurvey-anxiety-output-1.png" width="662" height="373" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stresssurvey-anxiety-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Scatter of Anxiety vs StressSurvey with fitted OLS line (clusters reveal discretized proxy).
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>{'intercept': np.float64(-1.524), 'slope': np.float64(1.047), 'R2': np.float64(0.9011)}</code></pre>
</div>
</div>
</section>
<section id="question-3-bivariate-regression-analysis-with-time" class="level2">
<h2 class="anchored" data-anchor-id="question-3-bivariate-regression-analysis-with-time">Question 3 — Bivariate Regression Analysis with Time</h2>
<p><strong>Answer — Bivariate regression of Anxiety on Time</strong></p>
<ul>
<li>Model estimated: Anxiety = β0 + β1 × Time + ε</li>
<li>OLS estimates from the provided data (15 rows):
<ul>
<li>Intercept (β0) = -3.6801</li>
<li>Slope (β1) = 5.3406</li>
</ul></li>
<li>Inference and fit:
<ul>
<li>R-squared = 0.5630</li>
<li>Slope t = 4.093, p ≈ 0.00127 (significant)</li>
<li>Intercept t = -1.648, p ≈ 0.123 (not significant)</li>
</ul></li>
</ul>
<p><strong>Comparison to the true relationship:</strong></p>
<ul>
<li>The true data-generating equation is Anxiety = Stress + 0.1 × Time, so the true coefficient on Time is 0.1.</li>
<li>The bivariate slope of ≈5.34 is wildly larger than 0.1. This is classic omitted-variable bias: <code>Stress</code> is omitted, yet it explains the vast majority of Anxiety and is correlated with Time in this synthetic design (as Stress increases across clusters, Time nudges upward). As a result, the Time slope absorbs Stress’s effect, producing a severely inflated estimate.</li>
<li>The negative intercept (≈ -3.68) and only moderate R² (≈0.56) also signal that a single-predictor linear model is not capturing the true structure.</li>
</ul>
<p><strong>Conclusion:</strong> Interpreting the bivariate coefficient on Time as a causal effect would be profoundly misleading. It reflects both Time’s small true effect (0.1) and the co-movement of Time with Stress, which has a large true effect (1.0).</p>
<div id="1cdbff31" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     16.75
Date:                Sat, 08 Nov 2025   Prob (F-statistic):            0.00127
Time:                        15:38:55   Log-Likelihood:                -38.223
No. Observations:                  15   AIC:                             80.45
Df Residuals:                      13   BIC:                             81.86
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6801      2.233     -1.648      0.123      -8.504       1.144
Time           5.3406      1.305      4.093      0.001       2.522       8.160
==============================================================================
Omnibus:                        1.026   Durbin-Watson:                   0.661
Prob(Omnibus):                  0.599   Jarque-Bera (JB):                0.749
Skew:                          -0.162   Prob(JB):                        0.688
Kurtosis:                       1.955   Cond. No.                         5.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</section>
<section id="question-4-visualization-of-anxiety-vs-time" class="level2">
<h2 class="anchored" data-anchor-id="question-4-visualization-of-anxiety-vs-time">Question 4 — Visualization of Anxiety vs Time</h2>
<p><strong>Goal:</strong> Visualize Anxiety (y) against Time (x), overlay the bivariate OLS fit, and diagnose how omitted Stress distorts interpretation.</p>
<p><strong>Plot &amp; Fit Observations:</strong></p>
<ul>
<li>Points form several nearly vertical stacks because Time changes only slightly within each Stress level, while Anxiety jumps by entire Stress units. This yields tall vertical separations at similar Time values.</li>
<li>The fitted line is steep (slope ≈ 5.34) because small increases in Time coincide with large increases in Anxiety driven by higher Stress. The model attributes that co-movement to Time, inflating the slope.</li>
<li>Intercept is negative and outside the realistic Anxiety range, suggesting extrapolation problems at low Time.</li>
<li>Moderate R² (~0.56) despite a visually steep fit reflects that most variation in Anxiety is actually due to Stress, not Time.</li>
<li>Visual takeaway: a bivariate line through vertically separated clusters is not evidence that Time has a large causal effect; it’s evidence that Time and Stress are not disentangled in this specification.</li>
</ul>
<p><strong>Concise Conclusion:</strong> The plot is a textbook picture of omitted-variable bias. Without controlling for Stress, the Time–Anxiety line overstates Time’s effect and misleads causal interpretation.</p>
<div id="cell-fig-time-anxiety" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-time-anxiety" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-time-anxiety-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-time-anxiety-output-1.png" width="662" height="373" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-time-anxiety-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Scatter of Anxiety vs Time with fitted OLS line (vertical banding reveals omitted Stress).
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>{'intercept': np.float64(-3.6801), 'slope': np.float64(5.3406), 'R2': np.float64(0.563)}</code></pre>
</div>
</div>
</section>
<section id="question-5-multiple-regression-anxiety-on-stresssurvey-time" class="level2">
<h2 class="anchored" data-anchor-id="question-5-multiple-regression-anxiety-on-stresssurvey-time">Question 5 — Multiple Regression: Anxiety on StressSurvey + Time</h2>
<p><strong>Model:</strong> Anxiety = β0 + β1 × StressSurvey + β2 × Time + ε</p>
<p><strong>Expectation from data-generating process:</strong> True coefficients are β0 = 0, βStress = 1, βTime = 0.1. Because the model substitutes StressSurvey (a proxy) for true Stress, we expect distortions even in a multivariate setting.</p>
<p><strong>Estimated OLS coefficients (n = 15):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 5%">
<col style="width: 15%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Estimate</th>
<th>Std. Err</th>
<th>t</th>
<th>p-value</th>
<th>Comparison to Truth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>0.589</td>
<td>1.034</td>
<td>0.569</td>
<td>0.580</td>
<td>True intercept = 0 (estimate is imprecise but near zero)</td>
</tr>
<tr class="even">
<td>StressSurvey</td>
<td>1.427</td>
<td>0.172</td>
<td>8.287</td>
<td>2.62e-06</td>
<td>True Stress coefficient = 1 → proxy inflates effect because survey scaling is non-linear</td>
</tr>
<tr class="odd">
<td>Time</td>
<td>-2.780</td>
<td>1.111</td>
<td>-2.502</td>
<td>0.0278</td>
<td>True Time coefficient = 0.1 → estimate flips sign and magnitude due to proxy/collinearity</td>
</tr>
</tbody>
</table>
<p>Model fit metrics: R² = 0.935, Adjusted R² = 0.924, F-statistic p-value ≈ 7.5e-08. Although the model explains &gt;93% of variance, its coefficients are far from the true structural values.</p>
<p><strong>Key Interpretability Problems:</strong></p>
<ol type="1">
<li><strong>Proxy Non-Linearity:</strong> StressSurvey compresses lower stress values and exaggerates higher ones, inflating β1 above the true Stress effect (1.0). The model interprets survey increments as larger jumps in true Stress than they are.</li>
<li><strong>Coefficient Competition / Suppression:</strong> Because StressSurvey imperfectly captures Stress, the residual Stress variation that co-moves with Time causes β2 to swing negative. The model “attributes” Anxiety reductions to higher Time once survey-measured stress is held constant, even though the true Time effect is +0.1.</li>
<li><strong>False Sense of Security from Fit:</strong> High R² and significant t-stats suggest a great model, yet the estimates tell the wrong causal story (wrong magnitude and even direction for Time). Statistical significance does not rescue a misspecified proxy.</li>
<li><strong>Small Sample Sensitivity:</strong> With only 15 observations and collinearity between StressSurvey and Time, small measurement errors in the proxy can drastically shift β2.</li>
</ol>
<p><strong>Concise Conclusion:</strong> Multiple regression with the survey proxy plus Time appears statistically strong but completely misrepresents the true causal relationship: it overstates the stress effect and reverses the sign on Time. This demonstrates why relying on proxies and high R² alone can lead analysts to confidently report incorrect conclusions.</p>
<div id="23f94e61" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Sat, 08 Nov 2025   Prob (F-statistic):           7.54e-08
Time:                        15:38:56   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
{'R2': np.float64(0.935), 'AdjR2': np.float64(0.9242)}</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🎯 Remember the True Coefficients!
</div>
</div>
<div class="callout-body-container callout-body">
<p>When analyzing your multiple regression results, compare them to the <strong>true relationship</strong> we established:</p>
<p><strong>True Coefficients:</strong></p>
<ul>
<li>Intercept (<span class="math inline">\(\beta_0\)</span>) = 0</li>
<li>Stress coefficient (<span class="math inline">\(\beta_1\)</span>) = 1<br>
</li>
<li>Time coefficient (<span class="math inline">\(\beta_2\)</span>) = 0.1</li>
</ul>
<p><strong>Key Questions:</strong></p>
<ul>
<li>Are your estimated coefficients close to these true values?</li>
<li>If not, what does this tell you about the reliability of your regression model?</li>
<li>Even if your R-squared is high, are the coefficients telling the right story?</li>
</ul>
</div>
</div>
<section id="questions-to-answer-for-85-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-85-grade-on-challenge">Questions to Answer for 85% Grade on Challenge</h3>
</section>
</section>
<section id="question-6-multiple-regression-anxiety-on-stress-time" class="level2">
<h2 class="anchored" data-anchor-id="question-6-multiple-regression-anxiety-on-stress-time">Question 6 — Multiple Regression: Anxiety on Stress + Time</h2>
<p><strong>Model:</strong> Anxiety = β0 + β1 × Stress + β2 × Time + ε</p>
<p><strong>Estimated OLS coefficients (n = 15):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 5%">
<col style="width: 15%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Estimate</th>
<th>Std. Err</th>
<th>t</th>
<th>p-value</th>
<th>Comparison to Truth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>~ 0.0</td>
<td>2.44e-15</td>
<td>-1.538</td>
<td>0.150</td>
<td>True intercept = 0 → essentially zero (within numerical precision)</td>
</tr>
<tr class="even">
<td>Stress</td>
<td>1.0000</td>
<td>2.75e-16</td>
<td>3.63e+15</td>
<td>~0</td>
<td>Matches true βStress = 1</td>
</tr>
<tr class="odd">
<td>Time</td>
<td>0.1000</td>
<td>1.94e-15</td>
<td>5.16e+13</td>
<td>~0</td>
<td>Matches true βTime = 0.1</td>
</tr>
</tbody>
</table>
<p>Model fit metrics: R² = 1.000, Adjusted R² = 1.000.</p>
<p><strong>Interpretation:</strong> With the correctly measured Stress variable included alongside Time, the model perfectly recovers the true structural coefficients by construction of the dataset. This provides a clean benchmark to contrast against models that use the survey proxy.</p>
<div id="b41ede83" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.511e+31
Date:                Sat, 08 Nov 2025   Prob (F-statistic):          3.92e-183
Time:                        15:38:56   Log-Likelihood:                 480.58
No. Observations:                  15   AIC:                            -955.2
Df Residuals:                      12   BIC:                            -953.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.747e-15   2.44e-15     -1.538      0.150   -9.05e-15    1.56e-15
Stress         1.0000   2.75e-16   3.63e+15      0.000       1.000       1.000
Time           0.1000   1.94e-15   5.16e+13      0.000       0.100       0.100
==============================================================================
Omnibus:                       10.194   Durbin-Watson:                   0.236
Prob(Omnibus):                  0.006   Jarque-Bera (JB):                2.265
Skew:                          -0.438   Prob(JB):                        0.322
Kurtosis:                       1.310   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</section>
<section id="question-7-model-comparison-proxy-vs.-true-stress" class="level2">
<h2 class="anchored" data-anchor-id="question-7-model-comparison-proxy-vs.-true-stress">Question 7 — Model Comparison (Proxy vs.&nbsp;True Stress)</h2>
<p><strong>Models compared:</strong></p>
<ul>
<li>Model A (Q5): Anxiety ~ StressSurvey + Time → R² = 0.935, Adj R² = 0.924
<ul>
<li>βStressSurvey ≈ 1.427 (p ≈ 2.6e-06)</li>
<li>βTime ≈ -2.780 (p ≈ 0.028)</li>
</ul></li>
<li>Model B (Q6): Anxiety ~ Stress + Time → R² = 1.000, Adj R² = 1.000
<ul>
<li>βStress = 1.000 (p ≈ 0)</li>
<li>βTime = 0.100 (p ≈ 0)</li>
</ul></li>
</ul>
<p><strong>Findings:</strong></p>
<ol type="1">
<li><strong>Fit vs.&nbsp;Truth:</strong> Model A has a very high R² but still tells the wrong causal story (inflated stress effect, negative time effect). Model B recovers the exact true coefficients. High R² alone is not a guarantee of correct interpretation.</li>
<li><strong>Significance ≠ Correctness:</strong> Model A yields statistically significant coefficients—even for the wrong sign on Time. Statistical significance can coexist with interpretive error when proxies or functional forms are misspecified.</li>
<li><strong>Proxy Hazard:</strong> Substituting StressSurvey for true Stress distorts both magnitudes and directions. The proxy’s non-linear scaling and collinearity with Time create suppression effects that flip βTime negative.</li>
<li><strong>Real-World Implication:</strong> Analysts and decision-makers could be persuaded by Model A’s strong-looking metrics and p-values, leading to incorrect conclusions about social media time “reducing” anxiety, which is the opposite of the true +0.1 effect per unit time.</li>
</ol>
<p><strong>Conclusion:</strong> When the correctly measured variable is available (here, true Stress), multiple regression can recover the true relationships. When only a proxy is available, even sophisticated-looking models can be confidently wrong. Always question proxies, inspect functional form, and validate against theory/ground truth when possible.</p>
<section id="questions-to-answer-for-95-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-95-grade-on-challenge">Questions to Answer for 95% Grade on Challenge</h3>
</section>
</section>
<section id="question-8-real-world-headlines-stakeholder-reactions" class="level2">
<h2 class="anchored" data-anchor-id="question-8-real-world-headlines-stakeholder-reactions">Question 8 — Real-World Headlines &amp; Stakeholder Reactions</h2>
<p><strong>Model A (Proxy: Anxiety ~ StressSurvey + Time)</strong> - Findings: βStressSurvey ≈ 1.43 (inflated), βTime ≈ -2.78 (sign-flipped), high R². - Likely Academic Abstract Spin: “Survey-measured stress strongly predicts anxiety; time online shows a negative association.” - Popular Press Headline: “More Social Media Time May LOWER Anxiety, Surprising Study Finds.” - Parent Reaction: Skeptical but some may welcome a narrative that screen time isn’t harmful (confirmation for parents who allow heavy usage). - Platform Executive Reaction: Enthusiastic—used defensively in PR to argue their products ‘may reduce anxiety’ when controlling for stress.</p>
<p><strong>Model B (True: Anxiety ~ Stress + Time)</strong> - Findings: βStress = 1.0, βTime = 0.1 (small positive), perfect fit to truth. - Popular Press Headline: “Study Confirms Social Media Slightly Raises Anxiety After Accounting for Stress.” - Parent Reaction: More alarming; reinforces pre-existing concerns about social media. - Platform Executive Reaction: Less favorable; downplays or challenges the ‘small but positive’ effect.</p>
<p><strong>Confirmation Bias Dynamics:</strong> Parents predisposed to worry about screen time will amplify Model B; tech companies and users preferring reassuring narratives will circulate Model A. Despite its <em>incorrect</em> causal interpretation, Model A’s dramatic (and counterintuitive) negative coefficient on Time has higher viral potential (“social media might help!”) and therefore greater misuse risk.</p>
<p><strong>Core Message:</strong> Spurious or proxy-driven coefficient flips can fuel misleading headlines, polarize stakeholders, and delay constructive policy discussions about genuine effects.</p>
<section id="questions-to-answer-for-100-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-100-grade-on-challenge">Questions to Answer for 100% Grade on Challenge</h3>
</section>
</section>
<section id="question-9-subset-statistical-regime-analysis" class="level2">
<h2 class="anchored" data-anchor-id="question-9-subset-statistical-regime-analysis">Question 9 — Subset (Statistical Regime) Analysis</h2>
<p><strong>Goal:</strong> Show how focusing on a regime where the proxy is nearly a linear transformation of true Stress recovers near-true coefficients, mitigating proxy distortion.</p>
<p><strong>Subset Chosen:</strong> Observations with true Stress ≤ 2 (the low-stress regime). Here, Stress values are {0,1,2}; corresponding StressSurvey values are {0,3,6}. This regime exhibits a consistent linear mapping: StressSurvey = 3 × Stress (exact scaling), preserving proportionality.</p>
<p><strong>Reason for Choice:</strong> Within this restricted range the proxy distortion vanishes (pure linear scaling). Omitted-variable issues are minimized because survey increments reflect uniform steps in true Stress; Time variation is modest and additive.</p>
<p><strong>Regression (Anxiety ~ StressSurvey + Time) on Subset (n=9):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 42%">
<col style="width: 12%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Estimate</th>
<th>Expected (Transformed Truth)</th>
<th>p-value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>~0.0</td>
<td>0</td>
<td>0.63</td>
<td>Near zero; no systematic bias</td>
</tr>
<tr class="even">
<td>StressSurvey</td>
<td>0.3333</td>
<td>1 / 3 (since Stress = StressSurvey / 3)</td>
<td>~0</td>
<td>Matches scaled true Stress effect</td>
</tr>
<tr class="odd">
<td>Time</td>
<td>0.1000</td>
<td>0.1</td>
<td>~0</td>
<td>Matches true Time effect</td>
</tr>
</tbody>
</table>
<p>Model fit: R² = 1.000 (design is perfectly consistent with structural equation in this subset).</p>
<p><strong>Interpretation:</strong> When the proxy is a simple linear scaling of the true variable (StressSurvey = 3 × Stress), the multiple regression correctly recovers scaled structural coefficients even with the proxy. This contrasts sharply with the full sample where non-linear jumps (e.g., Stress 2 → 8) break proportionality and flip the Time sign.</p>
<p><strong>Diagnostic Insight:</strong> Subsetting by regimes where linearity plausibly holds (low-stress consistent scaling) plus comparing coefficients to theoretical transformations provides a guardrail against misreading proxy-driven distortions. Graphical diagnostics (cluster spacing, stepwise jumps) would have alerted us to non-linearity outside the chosen subset.</p>
<p><strong>Conclusion:</strong> Strategic regime selection reveals when linear regression can be trusted with a proxy. The full-sample negative Time coefficient was an artifact; within a properly chosen regime, both coefficients align with the true causal structure, demonstrating the value of subset analysis for interpretability.</p>
<div id="72d8f565" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 4.892e+30
Date:                Sat, 08 Nov 2025   Prob (F-statistic):           2.31e-91
Time:                        15:38:56   Log-Likelihood:                 301.52
No. Observations:                   9   AIC:                            -597.0
Df Residuals:                       6   BIC:                            -596.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const        -3.386e-16   6.61e-16     -0.512      0.627   -1.96e-15    1.28e-15
StressSurvey     0.3333   2.27e-16   1.47e+15      0.000       0.333       0.333
Time             0.1000   8.87e-16   1.13e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        4.107   Durbin-Watson:                   0.613
Prob(Omnibus):                  0.128   Jarque-Bera (JB):                2.122
Skew:                           1.174   Prob(JB):                        0.346
Kurtosis:                       2.615   Cond. No.                         15.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🎯 For 100% Grade: Focus on What’s Most Interesting
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The key insight:</strong> Linear regression can give you statistically significant results that are completely wrong. The challenge is understanding when and why this happens.</p>
<p><strong>What to investigate:</strong></p>
<ul>
<li><strong>Coefficient Interpretation:</strong> What do the regression coefficients actually mean in this context?</li>
<li><strong>The Problem of Non-Linearity:</strong> Can adding variables to a regression equation flip the sign of a coefficient while still making it appear significant?</li>
</ul>
<p><strong>Write like a data science consultant:</strong> Your report should help someone understand not just what the numbers show, but why they’re dangerous and what to do about it.</p>
</div>
</div>
</section>
<section id="technical-implementation-preferences" class="level2">
<h2 class="anchored" data-anchor-id="technical-implementation-preferences">Technical Implementation Preferences 💡</h2>
<section id="setting-up-your-analysis" class="level3">
<h3 class="anchored" data-anchor-id="setting-up-your-analysis">Setting Up Your Analysis</h3>
<ul>
<li>Use <code>pandas</code> for data manipulation</li>
<li>Use <code>matplotlib</code> and <code>seaborn</code> for visualizations</li>
<li>Use <code>sklearn.linear_model</code> for regression analysis</li>
<li>Use <code>statsmodels</code> for detailed regression output</li>
</ul>
</section>
<section id="visualization-preferences" class="level3">
<h3 class="anchored" data-anchor-id="visualization-preferences">Visualization Preferences</h3>
<ul>
<li><strong>Professional Styling:</strong> Use consistent colors, clear labels, readable fonts, and informative titles</li>
</ul>
</section>
</section>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist ✅</h2>
<p><strong>Minimum Requirements (Required for Any Points):</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Forked starter repository from <a href="https://github.com/flyaflya/regressionChallenge.git">https://github.com/flyaflya/regressionChallenge.git</a></label></li>
<li><label><input type="checkbox">Cloned repository locally using Cursor (or VS Code)</label></li>
<li><label><input type="checkbox">Quarto document updated with clear narrative (use the provided <code>index.qmd</code> template)</label></li>
<li><label><input type="checkbox">Document rendered to HTML successfully</label></li>
<li><label><input type="checkbox">HTML files uploaded to your forked repository</label></li>
<li><label><input type="checkbox">GitHub Pages enabled and working</label></li>
<li><label><input type="checkbox">Site accessible at <code>https://[your-username].github.io/regressionChallenge/</code></label></li>
</ul>
<p><strong>75% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Bivariate regression analysis with StressSurvey and coefficient interpretation (Question 1)</label></li>
<li><label><input type="checkbox">Scatter plot with regression line for StressSurvey and interpretation (Question 2)</label></li>
<li><label><input type="checkbox">Bivariate regression analysis with Time and coefficient interpretation (Question 3)</label></li>
<li><label><input type="checkbox">Scatter plot with regression line for Time and interpretation (Question 4)</label></li>
<li><label><input type="checkbox">Multiple regression analysis with StressSurvey and Time and coefficient comparison (Question 5)</label></li>
</ul>
<p><strong>85% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Multiple regression analysis with Stress and Time (Question 6)</label></li>
<li><label><input type="checkbox">Model comparison analysis between StressSurvey and Stress models (Question 7)</label></li>
</ul>
<p><strong>95% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Real-world implications and headline analysis (Question 8)</label></li>
</ul>
<p><strong>100% Grade Requirements:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Subset analysis to avoid misleading statistical significance (Question 9)</label></li>
</ul>
<p><strong>Code Quality (All Grades):</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Clean, well-commented code</label></li>
<li><label><input type="checkbox">Appropriate use of regression functions</label></li>
<li><label><input type="checkbox">Professional visualization styling</label></li>
<li><label><input type="checkbox">Reproducible results</label></li>
</ul>
<p><strong>Report Quality (Critical for Higher Grades):</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Report structured as question and answer format (each question clearly stated, followed by answer)</label></li>
<li><label><input type="checkbox">All challenge instructions, setup guides, and grading rubrics removed from final HTML</label></li>
<li><label><input type="checkbox">Final report contains only Q&amp;A responses, code outputs, and visualizations</label></li>
<li><label><input type="checkbox">Clear, engaging narrative that tells a story</label></li>
<li><label><input type="checkbox">Focus on the most interesting findings about regression interpretability</label></li>
<li><label><input type="checkbox">Professional writing style (no AI-generated fluff)</label></li>
<li><label><input type="checkbox">Concise analysis that gets to the point</label></li>
<li><label><input type="checkbox">Practical insights that would help a real data scientist</label></li>
<li><label><input type="checkbox">Visualizations that support your narrative, not overwhelm it</label></li>
</ul>
<section id="resources" class="level3">
<h3 class="anchored" data-anchor-id="resources">Resources</h3>
<ul>
<li><strong>Quarto Markdown:</strong> <a href="https://quarto.org/docs/authoring/markdown-basics.html">quarto.org/docs/authoring/markdown-basics.html</a></li>
<li><strong>Quarto Documentation:</strong> <a href="https://quarto.org/docs">quarto.org/docs</a></li>
<li><strong>Python Data Science Handbook:</strong> <a href="https://jakevdp.github.io/PythonDataScienceHandbook">jakevdp.github.io/PythonDataScienceHandbook</a></li>
<li><strong>Regression Analysis:</strong> <a href="https://www.statlearning.com/">An Introduction to Statistical Learning</a></li>
</ul>
</section>
</section>
<section id="sec-regression-concepts" class="level2">
<h2 class="anchored" data-anchor-id="sec-regression-concepts">Essential Regression Concepts 🎯</h2>
<p>Before diving into the challenge, let’s review the key regression concepts you’ll need. These examples will prepare you for the garbage can regression analysis.</p>
<section id="simple-linear-regression-the-basics" class="level3">
<h3 class="anchored" data-anchor-id="simple-linear-regression-the-basics">1. Simple Linear Regression: The Basics</h3>
<p>Let’s start with a basic linear regression to understand the mechanics:</p>
<div id="simple-regression-python" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> r2_score</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">123</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create simple example data</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.random.normal(<span class="dv">10</span>, <span class="dv">3</span>, n)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> x <span class="op">+</span> <span class="dv">3</span> <span class="op">+</span> np.random.normal(<span class="dv">0</span>, <span class="dv">2</span>, n)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit linear regression</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression()</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>model.fit(x.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), y)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Coefficient: </span><span class="sc">{</span>model<span class="sc">.</span>coef_[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Intercept: </span><span class="sc">{</span>model<span class="sc">.</span>intercept_<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R-squared: </span><span class="sc">{</span>r2_score(y, model.predict(x.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)))<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scatter plot with regression line</span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">4</span>))</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>ax.scatter(x, y, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>ax.plot(x, model.predict(x.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)), color<span class="op">=</span><span class="st">'red'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Simple Linear Regression'</span>)</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'X Variable'</span>)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Y Variable'</span>)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="multiple-regression-adding-complexity" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-adding-complexity">2. Multiple Regression: Adding Complexity</h3>
<p>Now let’s see how multiple variables interact:</p>
<div id="multiple-regression-python" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> r2_score</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">456</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create multiple regression example</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>x1 <span class="op">=</span> np.random.normal(<span class="dv">10</span>, <span class="dv">3</span>, n)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>x2 <span class="op">=</span> np.random.normal(<span class="dv">5</span>, <span class="dv">2</span>, n)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> x1 <span class="op">+</span> <span class="fl">0.5</span> <span class="op">*</span> x2 <span class="op">+</span> <span class="dv">3</span> <span class="op">+</span> np.random.normal(<span class="dv">0</span>, <span class="dv">2</span>, n)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit multiple regression</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.column_stack([x1, x2])</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>model_multi <span class="op">=</span> LinearRegression()</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>model_multi.fit(X, y)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Coefficients: </span><span class="sc">{</span>model_multi<span class="sc">.</span>coef_<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Intercept: </span><span class="sc">{</span>model_multi<span class="sc">.</span>intercept_<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R-squared: </span><span class="sc">{</span>r2_score(y, model_multi.predict(X))<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Create pairs plot</span></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>data_df <span class="op">=</span> pd.DataFrame({<span class="st">'x1'</span>: x1, <span class="st">'x2'</span>: x2, <span class="st">'y'</span>: y})</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>sns.pairplot(data_df)</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Pairs Plot: Multiple Regression Variables'</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Statistical Significance at 5% Level
</div>
</div>
<div class="callout-body-container callout-body">
<p>A coefficient is <strong>statistically significant</strong> when its p-value is less than 0.05.</p>
<ul>
<li><strong>p &lt; 0.05</strong>: Statistically significant</li>
<li><strong>p ≥ 0.05</strong>: Not statistically significant</li>
</ul>
<section id="understanding-scientific-notation-in-p-values" class="level3">
<h3 class="anchored" data-anchor-id="understanding-scientific-notation-in-p-values">Understanding Scientific Notation in P-values</h3>
<p>Sometimes you’ll see p-values written in scientific notation like <code>7.89e-4</code>. Don’t panic! This is just a way to write very small numbers:</p>
<ul>
<li><strong>7.89e-4</strong> means 7.89 × 10⁻⁴ = 0.000789</li>
<li><strong>2.34e-6</strong> means 2.34 × 10⁻⁶ = 0.00000234</li>
<li><strong>1.23e-2</strong> means 1.23 × 10⁻² = 0.0123</li>
</ul>
<p><strong>The key rule:</strong> If you see “e-” in a p-value, it’s always a very small number (less than 1). The number after “e-” tells you how many zeros come before the first non-zero digit.</p>
<p><strong>Examples:</strong> - 7.89e-4 = 0.000789 (less than 0.05, so significant!) - 2.34e-6 = 0.00000234 (way less than 0.05, so very significant!) - 1.23e-2 = 0.0123 (less than 0.05, so significant!)</p>
<p><strong>Remember:</strong> Statistical significance doesn’t mean the effect is large or important - it just means we’re confident the effect isn’t zero.</p>
</section>
</div>
</div>
</section>
</section>
<section id="the-problem-of-non-linearity-a-deeper-look" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-of-non-linearity-a-deeper-look">The Problem of Non-Linearity: A Deeper Look</h2>
<p>The “garbage can regression” problem occurs when we include variables in our regression models that create misleading results, even when they appear statistically significant. This happens in several ways:</p>
<ol type="1">
<li><strong>Random correlations:</strong> Even random variables can appear correlated by chance</li>
<li><strong>Overfitting:</strong> More variables can improve fit without improving understanding</li>
<li><strong>Multiple testing:</strong> The more variables we test, the more likely we are to find spurious relationships</li>
<li><strong>Non-linear relationships:</strong> Variables with U-shaped, exponential, or other non-linear relationships with the outcome are forced into a linear framework, creating misleading coefficients</li>
</ol>
<section id="why-this-matters" class="level3">
<h3 class="anchored" data-anchor-id="why-this-matters">Why This Matters</h3>
<p>In the real world, non-linear relationships can lead to:</p>
<ul>
<li><strong>False policy recommendations:</strong> Basing decisions on spurious correlations or false causal relationships</li>
<li><strong>Wasted resources:</strong> Pursuing interventions that don’t actually work</li>
<li><strong>Loss of credibility:</strong> When results can’t be replicated or don’t make sense</li>
<li><strong>Ethical issues:</strong> Making decisions that affect people’s lives based on bad science</li>
</ul>
</section>
<section id="the-solution" class="level3">
<h3 class="anchored" data-anchor-id="the-solution">The Solution</h3>
<p>The key is to always ask:</p>
<ol type="1">
<li><strong>Does this make theoretical sense?</strong> Is there a plausible mechanism?</li>
<li><strong>Is the relationship robust?</strong> Does it hold across different samples and specifications?</li>
<li><strong>Are we overfitting?</strong> Do we have enough data relative to the number of variables?</li>
<li><strong>Can we interpret the coefficients?</strong> Do the results tell a coherent story?</li>
<li><strong>Is the relationship truly linear?</strong> Check for non-linear patterns that linear regression can’t capture</li>
<li><strong>Are we forcing the wrong functional form?</strong> Consider if polynomial terms, interactions, or transformations are needed</li>
<li><strong>Split the sample into meaningful subsets:</strong> Analyze different “statistical regimes” to see if relationships hold consistently across different parts of your data</li>
<li><strong>Use graphical diagnostics:</strong> Don’t rely blindly on “canned” regressions—visualize the relationships to understand what’s really happening</li>
</ol>
<p>Remember: <strong>Correlation is not causation, and regression coefficients can lie!</strong> 📊</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>